# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Training
    url: training/
    weight: 40
  - name: Presentations
    url: presentations/
    weight: 50
- name: Community
    url: community/
    weight: 60
- name: Offensive Security Notes
    url: docs/
    weight: 70
- name: Contact
    url: contact/
    weight: 80

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
